import { Rocket, Repeat, BarChart3, Sparkles } from 'lucide-react';

const items = [
  {
    icon: Rocket,
    title: 'Reduce Customer Acquisition Cost',
    desc: 'Target high-intent segments with creative and channel recommendations generated by fine-tuned models.',
    stat: '18–32% CAC drop',
  },
  {
    icon: Repeat,
    title: 'Recapture Abandoned Cart Revenue',
    desc: 'Real-time triggers craft on-brand emails/SMS with incentives tuned to probability-to-convert.',
    stat: '+12–20% revenue recapture',
  },
  {
    icon: BarChart3,
    title: 'Predictive LTV & Cohorts',
    desc: 'Forecast LTV and churn windows to optimize offers, budgets, and inventory allocation.',
    stat: 'Up to 25% ROAS lift',
  },
  {
    icon: Sparkles,
    title: 'Personalized On-site Experiences',
    desc: 'AI merchandising, copy, and bundles that adapt to each shopper’s intent in milliseconds.',
    stat: '+8–15% conversion rate',
  },
];

export default function Solutions() {
  return (
    <section id="solutions" className="relative w-full bg-slate-950 py-20">
      <div className="max-w-6xl mx-auto px-6">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-semibold text-white">Outcomes that move the P&L</h2>
          <p className="mt-3 text-white/70 max-w-2xl mx-auto">
            Deploy specialized models across your funnel. Start with one module or roll out the full SilverSynth stack.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {items.map(({ icon: Icon, title, desc, stat }) => (
            <div key={title} className="group rounded-2xl border border-white/10 bg-gradient-to-b from-white/5 to-white/0 p-5 backdrop-blur hover:border-white/20 transition">
              <div className="inline-flex h-10 w-10 items-center justify-center rounded-lg bg-white/10 text-white">
                <Icon size={20} />
              </div>
              <h3 className="mt-4 text-lg font-semibold text-white">{title}</h3>
              <p className="mt-2 text-sm text-white/70">{desc}</p>
              <div className="mt-4 text-emerald-300 text-sm font-medium">{stat}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
